name: Deployment
run-name: ${{ github.actor }} is running 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
  with:
    node-version: 22
    name: Build
    - uses: actions/checkout@v3
    steps:
      - run: npm install -g @angular/cli
      - run: npm run build
  # test:
  # needs: [test]
  #   name: Testing

  # deploy:
  #   needs: [build, test]
  #   name: Deployment